language: node_js
sudo: false
node_js:
  - 8.14
  - 10.13
  - 11
  - 12
env:
    - AWS_DEFAULT_REGION=eu-west-1 AWS_ACCESS_KEY_ID=dummy AWS_SECRET_ACCESS_KEY=dummy
before_install:
  - git clone https://github.com/Linuxbrew/brew.git ~/.linuxbrew
  - export HOMEBREW_FORCE_VENDOR_RUBY=1
install:
  - travis_retry npm ci
  - travis_retry brew tap aws/tap
  - travis_retry brew install aws-sam-cli
script:
  - travis_retry npm test
  - sam validate
after_success:
  - npm run coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
