language: node_js
sudo: false
node_js:
  - 8.14
  - 10.13
  - 11
  - 12
env:
  # env variable needed by AWS SAM CLI
  - AWS_DEFAULT_REGION=eu-west-1 AWS_ACCESS_KEY_ID=dummy AWS_SECRET_ACCESS_KEY=dummy
install:
  # install Node.js dependencies
  - travis_retry npm ci
  # install AWS SAM CLI
  - pip install aws-sam-cli --user
script:
  # run test suite
  - travis_retry npm test
  # validate YAML template
  - sam validate
after_success:
  # udpate coverate stats
  - npm run coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
